"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestDomainValidationMagritteCore,
	#superclass : #PackageManifest,
	#category : 'DomainValidationMagritte-Core'
}

{ #category : #'code-critics' }
ManifestDomainValidationMagritteCore class >> ruleRBCollectSelectNotUsedRuleV1FalsePositive [
	^ #(#(#(#RGPackage #(#'DomainValidationMagritte-Core')) #'2018-10-19T22:09:43.602226-03:00') )
]
