"
I am a test data class.
"
Class {
	#name : #DvmClassToLinkValidations,
	#superclass : #Object,
	#category : 'DomainValidationMagritte-Tests-Link'
}

{ #category : #fake }
DvmClassToLinkValidations >> @ param [
	"Validation should be performed by magritte generated validations Context returned for testing."

]

{ #category : #fake }
DvmClassToLinkValidations >> p1: p1 [
	"Validation should be performed by magritte generated validations."
]

{ #category : #fake }
DvmClassToLinkValidations >> p1: p1 p2: p2 [
	"Validation should be performed by magritte generated validations Context returned for testing."

]

{ #category : #fake }
DvmClassToLinkValidations >> p1: p1 p2: p2 p3: p3 [
	"Validation should be performed by magritte generated validations Context returned for testing."

]
